[email]
sender = "test@gmail.com"
password = "jwal sfhf dhkv ljhi"
to = "test@gmail.com"
smtp_host = "smtp.gmail.com"
smtp_port = 587

[twilio]
sid = "AC0cc7791d7297aa3f0b2a728d5f2759xx"
token = "1da07f3ae67d23249b51b8bc01a5bfxx"
from_ = "+16627074842"
# Optional alternative to from_:
messaging_service_sid = "MG3734f082088f9c430c197501f322exx"
